"""
3 letter aa
"""

protein_letters_1to3 = {
    "A": "Ala",
    "C": "Cys",
    "D": "Asp",
    "E": "Glu",
    "F": "Phe",
    "G": "Gly",
    "H": "His",
    "I": "Ile",
    "K": "Lys",
    "L": "Leu",
    "M": "Met",
    "N": "Asn",
    "P": "Pro",
    "Q": "Gln",
    "R": "Arg",
    "S": "Ser",
    "T": "Thr",
    "V": "Val",
    "W": "Trp",
    "Y": "Tyr",
}

three_letter = []
for index in protein_letters_1to3:
    three_letter.append(protein_letters_1to3[index].upper())

df_def = {'sphere_radius':[],
        'natom':[],
        'ntypes':[],
        'nbonh':[],
        'natom':[],
        'mbona':[],
        'ntheth':[],
        'mtheta':[],
        'nphih':[],
        'mphia':[],
        'nhparm':[],
        'nparm':[],
        'nnb':[],
        'nres':[],
        'nbona':[],
        'ntheta':[],
        'nphia':[],
        'numbnd':[],
        'numang':[],
        'nptra':[],
        'natyp':[],
        'nphb':[],
        'ifbox':[],
        'nmxrs':[],
        'ifcap':[],
        'nextra':[],
        'ncopy':[],
        'imin':[],
        'nmropt':[],
        'ntx':[],
        'irest':[],
        'ntrxi':[],
        'ntxo':[],
        'ntpr':[],
        'ntrxo':[],
        'ntwr':[],
        'iwrap':[],
        'ntwx':[],
        'ntwv':[],
        'ntwe':[],
        'ioutfm':[],
        'ntwprt':[],
        'idecomp':[],
        'rbornstat':[],
        'ntf':[],
        'ntb':[],
        'igb':[],
        'nsnb':[],
        'ipol':[],
        'gbsa':[],
        'iesp':[],
        'dielc':[],
        'cut':[],
        'intdiel':[],
        'ibelly':[],
        'ntr':[],
        'nstlim':[],
        'nscm':[],
        'nrespa':[],
        't':[],
        'dt':[],
        'vlimit':[],
        'ig':[],
        'temp0':[],
        'tempi':[],
        'gamma_ln':[],
        'ntc':[],
        'jfastw':[],
        'tol':[],
        'sum_charges':[],
        'rndfp':[],
        'rndfs':[],
        'ndfmin':[],
        'num_noshake':[],
        'corrected_rndfp':[],
        'rndf':[],
        'local_nonbond':[],
        'total_nonbond':[],
        'avg_nstep':[],
        'avg_time_ps':[],
        'avg_temp_k':[],
        'avg_press':[],
        'avg_etot':[],
        'avg_ektot':[],
        'avg_eptot':[],
        'avg_bond':[],
        'avg_angle':[],
        'avg_dihed':[],
        'avg_nb':[],
        'avg_eel':[],
        'avg_vdwaals':[],
        'avg_eelec':[],
        'avg_ehbond':[],
        'avg_restraint':[],
        'rmsf_nstep':[],
        'rmsf_time_ps':[],
        'rmsf_temp_k':[],
        'rmsf_press':[],
        'rmsf_etot':[],
        'rmsf_ektot':[],
        'rmsf_eptot':[],
        'rmsf_bond':[],
        'rmsf_angle':[],
        'rmsf_dihed':[],
        'rmsf_nb':[],
        'rmsf_eel':[],
        'rmsf_vdwaals':[],
        'rmsf_eelec':[],
        'rmsf_ehbond':[],
        'rmsf_restraint':[]
       }
